### PR TITLE
[No Jira] Preparing release of uimaFIT 2.5.0

### PR DESCRIPTION
**Pull request by reckart**
This PR tracks the release of uimaFIT 2.5.0.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/69/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/75/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/79/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/85/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/88/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/91/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/92/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/98/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/128/

**Comment by reckart** [comment]
Test

**Pull request merged**
