### PR TITLE
[UIMA-5323] Adjust uimaFIT v3 branch to actually build against UIMA v3

### PR DESCRIPTION
**Pull request by reckart**
- Fix bad parent version
- Depend on UIMA 3.0.0 (release version)

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/1/<h2>Build result: FAILURE</span></h2>[...truncated 225.29 KB...]	at org.apache.maven.plugin.invoker.model.io.xpp3.BuildJobXpp3Reader.read(BuildJobXpp3Reader.java:558)	at org.jenkinsci.plugins.maveninvoker.MavenInvokerArchiver.postExecute(MavenInvokerArchiver.java:113)	at hudson.maven.Maven3Builder$MavenExecutionListener.recordMojoEnded(Maven3Builder.java:629)	at hudson.maven.Maven3Builder$MavenExecutionListener.mojoSucceeded(Maven3Builder.java:610)	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:87)	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:228)	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)	... 21 morechannel stopped[Set GitHub commit status (universal)] PENDING on repos [GHRepository@6b3f711b[description=Apache UIMA uimafit,homepage=,name=uima-uimafit,fork=false,size=1271,milestones={},language=Java,commits={},source=<null>,parent=<null>,responseHeaderFields={null=[HTTP/1.1 200 OK], Access-Control-Allow-Origin=[*], Access-Control-Expose-Headers=[ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval], Cache-Control=[private, max-age=60, s-maxage=60], Content-Encoding=[gzip], Content-Security-Policy=[default-src 'none'], Content-Type=[application/json; charset=utf-8], Date=[Fri, 18 May 2018 20:53:25 GMT], ETag=[W/"8679b116155e94a6b73be8683f7ca736"], Last-Modified=[Thu, 26 Apr 2018 17:18:45 GMT], OkHttp-Received-Millis=[1526676805608], OkHttp-Response-Source=[NETWORK 200], OkHttp-Selected-Protocol=[http/1.1], OkHttp-Sent-Millis=[1526676805460], Referrer-Policy=[origin-when-cross-origin, strict-origin-when-cross-origin], Server=[GitHub.com], Status=[200 OK], Strict-Transport-Security=[max-age=31536000; includeSubdomains; preload], Transfer-Encoding=[chunked], Vary=[Accept, Authorization, Cookie, X-GitHub-OTP], X-Accepted-OAuth-Scopes=[repo], X-Content-Type-Options=[nosniff], X-Frame-Options=[deny], X-GitHub-Media-Type=[github.v3; format=json], X-GitHub-Request-Id=[A206:6B0D:29BF82C:53DA470:5AFF3D3E], X-OAuth-Scopes=[admin:repo_hook, repo, repo:status], X-RateLimit-Limit=[5000], X-RateLimit-Remaining=[4955], X-RateLimit-Reset=[1526676921], X-Runtime-rack=[0.066545], X-XSS-Protection=[1; mode=block]},url=https://api.github.com/repos/apache/uima-uimafit,id=15070665]] (sha:490f6f4) with context:Apache UIMA uimaFIT (GitHub PR)Setting commit status on GitHub for https://github.com/apache/uima-uimafit/commit/490f6f4d585dea11038584cfa22bebbdf84f9beaAdding one-line test results to commit status...Setting status of a0763c68be65902adabb31f705f7c6057853bb97 to FAILURE with url https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/1/ and message: 'FAILURE 203 tests run, 1 skipped, 0 failed.'Using context: default

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/2/<h2>Build result: FAILURE</span></h2>[...truncated 146.69 KB...]	at org.apache.maven.plugin.invoker.model.io.xpp3.BuildJobXpp3Reader.read(BuildJobXpp3Reader.java:558)	at org.jenkinsci.plugins.maveninvoker.MavenInvokerArchiver.postExecute(MavenInvokerArchiver.java:113)	at hudson.maven.Maven3Builder$MavenExecutionListener.recordMojoEnded(Maven3Builder.java:629)	at hudson.maven.Maven3Builder$MavenExecutionListener.mojoSucceeded(Maven3Builder.java:610)	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:87)	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:228)	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)	... 21 morechannel stopped[Set GitHub commit status (universal)] FAILURE on repos [GHRepository@6725bed8[description=Apache UIMA uimafit,homepage=,name=uima-uimafit,fork=false,size=1271,milestones={},language=Java,commits={},source=<null>,parent=<null>,responseHeaderFields={null=[HTTP/1.1 200 OK], Access-Control-Allow-Origin=[*], Access-Control-Expose-Headers=[ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval], Cache-Control=[private, max-age=60, s-maxage=60], Content-Encoding=[gzip], Content-Security-Policy=[default-src 'none'], Content-Type=[application/json; charset=utf-8], Date=[Fri, 18 May 2018 21:05:47 GMT], ETag=[W/"8679b116155e94a6b73be8683f7ca736"], Last-Modified=[Thu, 26 Apr 2018 17:18:45 GMT], OkHttp-Received-Millis=[1526677547994], OkHttp-Response-Source=[NETWORK 200], OkHttp-Selected-Protocol=[http/1.1], OkHttp-Sent-Millis=[1526677547864], Referrer-Policy=[origin-when-cross-origin, strict-origin-when-cross-origin], Server=[GitHub.com], Status=[200 OK], Strict-Transport-Security=[max-age=31536000; includeSubdomains; preload], Transfer-Encoding=[chunked], Vary=[Accept, Authorization, Cookie, X-GitHub-OTP], X-Accepted-OAuth-Scopes=[repo], X-Content-Type-Options=[nosniff], X-Frame-Options=[deny], X-GitHub-Media-Type=[github.v3; format=json], X-GitHub-Request-Id=[AA00:6B0D:29E450A:54226DB:5AFF4000], X-OAuth-Scopes=[admin:repo_hook, repo, repo:status], X-RateLimit-Limit=[5000], X-RateLimit-Remaining=[4981], X-RateLimit-Reset=[1526680613], X-Runtime-rack=[0.049508], X-XSS-Protection=[1; mode=block]},url=https://api.github.com/repos/apache/uima-uimafit,id=15070665]] (sha:490f6f4) with context:Apache UIMA uimaFIT (GitHub PR)Setting commit status on GitHub for https://github.com/apache/uima-uimafit/commit/490f6f4d585dea11038584cfa22bebbdf84f9beaAdding one-line test results to commit status...Setting status of a0763c68be65902adabb31f705f7c6057853bb97 to FAILURE with url https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/2/ and message: 'FAILURE 203 tests run, 1 skipped, 0 failed.'Using context: default

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Pull request merged**
