### PR TITLE
[no-jira] fix typo

### PR DESCRIPTION
**Pull request by mischor**
Replace ref to DKPRO with uimaFIT

### CODE REVIEW

**Comment by mischor** [comment]
hmmm, my tryout of a new editor, visual studio code, seems to have inserted some lines into a bunch of .settings files.  Those can be ommitted when cherry-picking the change :-)

**Comment by reckart** [comment]
Jenkins, can you test this please?

@mischor I have whitelisted you on Jenkins so that your PRs are now built without additional intervention.

**Comment by reckart** [comment]
@mischor I wouldn't cherry pick the PR, but rather merge it once Jenkins gives the thumbs up. The way to exclude these changes would be to do another commit which reverses the changes into the branch underlying this PR. I'll try doing that.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/83/

**Comment by reckart** [comment]
@mischor the second commit undoes the changes. Now, I could either create a "merge commit" which retains both of our commits, or I could merge this PR into the master branch using a "squash + commit" which would conflate both our commits into a single commit and then merge it into master. I'll probably go for the squash in this case :)

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/84/

**Pull request merged**
