### PR TITLE
[UIMA-3928] createExternalResourceDescription() signatures shadowing each other

### PR DESCRIPTION
**Pull request by reckart**
See: https://issues.apache.org/jira/browse/UIMA-3928

### CODE REVIEW

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/6/

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/7/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/9/

**Comment by reckart** [comment]
Jenkins, can you test this please?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/10/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/11/

**Pull request merged**
