### PR TITLE
[UIMA-5807] Support PEARs in AnalysisEngineFactory

### PR DESCRIPTION
**Pull request by reckart**
- Added new method createEngineDescription(PearSpecifier, params...)
- Added simple PEAR unit test (no parameters on the PEAR)

JIRA: https://issues.apache.org/jira/browse/UIMA-5807

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/73/

**Comment by pkluegl** [comment]
This looks good to me, but I need some time to test the consequences in our code. Unfortunately, I won't we able to do that in August.

**Comment by pkluegl** [comment]
That's fine for me :-)

**Comment by reckart** [comment]
@pkluegl since August is long past now an I'm about to finally finalize the uimaFIT 2.5.0/3.0.0 release ... did you meanwhile have any chance to look into this?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Apache%20UIMA%20uimaFIT%20(GitHub%20PR)/94/

**Pull request closed without merging**
